### ISSUE TITLE
ETGMod Installer error

### ISSUE THREAD

**Issue by cdwillia** [ModTheGungeon/ETGMod.Installer#12]
ETGMod Installer v17.3.8
Entering the Modgeon
Removing: Assembly-CSharp.Base.mm.dll
Removing: UnityEngine.Base.mm.dll
No previous mod installation found.
Still reverting to unmodded backup...
Reverting: EtG.exe
Reverting: Assembly-CSharp.dll
Reverting: UnityEngine.dll
Reloading Assembly-CSharp.dll
Backing up: UnityEngine.dll
Backing up: Assembly-CSharp.dll
Backing up: EtG.exe
Mod #0: Base
Reading from cache: ETGMOD.zip
Checking for ETGMOD/...
Entry: InstallerVersion.txt: 9 bytes
Found version file.
Entry: ETGMOD/Newtonsoft.Json.dll: 419840 bytes
Entry: ETGMOD/: 0 bytes
Entry: ETGMOD/Assembly-CSharp.Base.mm.dll: 316928 bytes
Entry: ETGMOD/I18N.CJK.dll: 680448 bytes
Entry: ETGMOD/I18N.MidEast.dll: 29184 bytes
Entry: ETGMOD/I18N.Other.dll: 32256 bytes
Entry: ETGMOD/I18N.Rare.dll: 171008 bytes
Entry: ETGMOD/I18N.West.dll: 65536 bytes
Entry: ETGMOD/I18N.dll: 31744 bytes
Entry: ETGMOD/Ionic.Zip.dll: 462336 bytes
Entry: ETGMOD/Mono.Cecil.dll: 369664 bytes
Entry: ETGMOD/PEG.dll: 89088 bytes
Entry: ETGMOD/UnityEngine.Base.mm.dll: 19968 bytes
Entry: ETGMOD/YamlDotNet.dll: 182272 bytes
Entry: ETGMOD/System.Xml.dll: 1270272 bytes
ETGMOD/ found.
Extracting: ETGMOD/Newtonsoft.Json.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Newtonsoft.Json.dll
Extracting: ETGMOD/Assembly-CSharp.Base.mm.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Assembly-CSharp.Base.mm.dll
Extracting: ETGMOD/I18N.CJK.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.CJK.dll
Extracting: ETGMOD/I18N.MidEast.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.MidEast.dll
Extracting: ETGMOD/I18N.Other.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.Other.dll
Extracting: ETGMOD/I18N.Rare.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.Rare.dll
Extracting: ETGMOD/I18N.West.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.West.dll
Extracting: ETGMOD/I18N.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\I18N.dll
Extracting: ETGMOD/Ionic.Zip.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Ionic.Zip.dll
Extracting: ETGMOD/Mono.Cecil.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\Mono.Cecil.dll
Extracting: ETGMOD/PEG.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\PEG.dll
Extracting: ETGMOD/UnityEngine.Base.mm.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\UnityEngine.Base.mm.dll
Extracting: ETGMOD/YamlDotNet.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\YamlDotNet.dll
Extracting: ETGMOD/System.Xml.dll -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\System.Xml.dll
Mod #1: ZIP: C:\Users\Cory\Downloads\ETGMod.Installer-17.03.29.1.zip
Checking for ETGMOD/...
Entry: ETGMod.Installer-17.03.29.1/: 0 bytes
Entry: ETGMod.Installer-17.03.29.1/.gitignore: 50 bytes
Entry: ETGMod.Installer-17.03.29.1/.gitmodules: 201 bytes
Entry: ETGMod.Installer-17.03.29.1/.travis.yml: 801 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/: 0 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/background.png: 64782 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/background.xcf: 607049 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/: 0 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/app.ico: 22446 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/error.gif: 6360 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/finished.gif: 34558 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/icon.png: 874 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/idle.png: 862 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/installing.gif: 38765 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/main-large.gif: 9997 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/main-large.png: 647 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/main.gif: 932 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/open.png: 266 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/robot.gif: 145 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/robut_wrench.png: 586 bytes
Entry: ETGMod.Installer-17.03.29.1/Assets/icons/uninstall.png: 252 bytes
Entry: ETGMod.Installer-17.03.29.1/ETGMod.Installer.csproj: 12801 bytes
Entry: ETGMod.Installer-17.03.29.1/ETGMod.Installer.csproj.user: 485 bytes
Entry: ETGMod.Installer-17.03.29.1/ETGMod.Installer.sln: 1464 bytes
Entry: ETGMod.Installer-17.03.29.1/LICENSE: 1077 bytes
Entry: ETGMod.Installer-17.03.29.1/Properties/: 0 bytes
Entry: ETGMod.Installer-17.03.29.1/Properties/AssemblyInfo.cs: 992 bytes
Entry: ETGMod.Installer-17.03.29.1/README.md: 1076 bytes
Entry: ETGMod.Installer-17.03.29.1/build.sh: 56 bytes
Entry: ETGMod.Installer-17.03.29.1/github-release.sh: 6433 bytes
Entry: ETGMod.Installer-17.03.29.1/lib-projs/: 0 bytes
Entry: ETGMod.Installer-17.03.29.1/lib-projs/MonoMod/: 0 bytes
Entry: ETGMod.Installer-17.03.29.1/lib-projs/cecil/: 0 bytes
Entry: ETGMod.Installer-17.03.29.1/replace-version.sh: 305 bytes
Entry: ETGMod.Installer-17.03.29.1/src/: 0 bytes
Entry: ETGMod.Installer-17.03.29.1/src/BinaryHelper.cs: 2399 bytes
Entry: ETGMod.Installer-17.03.29.1/src/ConfigParser/: 0 bytes
Entry: ETGMod.Installer-17.03.29.1/src/ConfigParser/Lexer.cs: 3400 bytes
Entry: ETGMod.Installer-17.03.29.1/src/ConfigParser/Parser.cs: 2396 bytes
Entry: ETGMod.Installer-17.03.29.1/src/CustomControls.cs: 2347 bytes
Entry: ETGMod.Installer-17.03.29.1/src/DeobfuscatorExt.cs: 994 bytes
Entry: ETGMod.Installer-17.03.29.1/src/ETGFinder.cs: 17680 bytes
Entry: ETGMod.Installer-17.03.29.1/src/ETGInstallerSettings.cs: 6277 bytes
Entry: ETGMod.Installer-17.03.29.1/src/ETGModder.cs: 35874 bytes
Entry: ETGMod.Installer-17.03.29.1/src/InstallerWindow.cs: 34398 bytes
Entry: ETGMod.Installer-17.03.29.1/src/RepoHelper.cs: 2945 bytes
Is this even a ETGMod ZIP? uh...
Extracting: ETGMod.Installer-17.03.29.1/ -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\
Extracting: ETGMod.Installer-17.03.29.1/.gitignore -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\.gitignore
Extracting: ETGMod.Installer-17.03.29.1/.gitmodules -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\.gitmodules
Extracting: ETGMod.Installer-17.03.29.1/.travis.yml -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\.travis.yml
Extracting: ETGMod.Installer-17.03.29.1/Assets/ -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\
Extracting: ETGMod.Installer-17.03.29.1/Assets/background.png -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\background.png
Extracting: ETGMod.Installer-17.03.29.1/Assets/background.xcf -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\background.xcf
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/ -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/app.ico -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\app.ico
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/error.gif -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\error.gif
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/finished.gif -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\finished.gif
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/icon.png -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\icon.png
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/idle.png -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\idle.png
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/installing.gif -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\installing.gif
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/main-large.gif -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\main-large.gif
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/main-large.png -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\main-large.png
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/main.gif -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\main.gif
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/open.png -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\open.png
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/robot.gif -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\robot.gif
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/robut_wrench.png -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\robut_wrench.png
Extracting: ETGMod.Installer-17.03.29.1/Assets/icons/uninstall.png -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Assets\icons\uninstall.png
Extracting: ETGMod.Installer-17.03.29.1/ETGMod.Installer.csproj -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\ETGMod.Installer.csproj
Extracting: ETGMod.Installer-17.03.29.1/ETGMod.Installer.csproj.user -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\ETGMod.Installer.csproj.user
Extracting: ETGMod.Installer-17.03.29.1/ETGMod.Installer.sln -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\ETGMod.Installer.sln
Extracting: ETGMod.Installer-17.03.29.1/LICENSE -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\LICENSE
Extracting: ETGMod.Installer-17.03.29.1/Properties/ -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Properties\
Extracting: ETGMod.Installer-17.03.29.1/Properties/AssemblyInfo.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\Properties\AssemblyInfo.cs
Extracting: ETGMod.Installer-17.03.29.1/README.md -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\README.md
Extracting: ETGMod.Installer-17.03.29.1/build.sh -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\build.sh
Extracting: ETGMod.Installer-17.03.29.1/github-release.sh -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\github-release.sh
Extracting: ETGMod.Installer-17.03.29.1/lib-projs/ -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\lib-projs\
Extracting: ETGMod.Installer-17.03.29.1/lib-projs/MonoMod/ -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\lib-projs\MonoMod\
Extracting: ETGMod.Installer-17.03.29.1/lib-projs/cecil/ -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\lib-projs\cecil\
Extracting: ETGMod.Installer-17.03.29.1/replace-version.sh -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\replace-version.sh
Extracting: ETGMod.Installer-17.03.29.1/src/ -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\
Extracting: ETGMod.Installer-17.03.29.1/src/BinaryHelper.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\BinaryHelper.cs
Extracting: ETGMod.Installer-17.03.29.1/src/ConfigParser/ -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\ConfigParser\
Extracting: ETGMod.Installer-17.03.29.1/src/ConfigParser/Lexer.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\ConfigParser\Lexer.cs
Extracting: ETGMod.Installer-17.03.29.1/src/ConfigParser/Parser.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\ConfigParser\Parser.cs
Extracting: ETGMod.Installer-17.03.29.1/src/CustomControls.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\CustomControls.cs
Extracting: ETGMod.Installer-17.03.29.1/src/DeobfuscatorExt.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\DeobfuscatorExt.cs
Extracting: ETGMod.Installer-17.03.29.1/src/ETGFinder.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\ETGFinder.cs
Extracting: ETGMod.Installer-17.03.29.1/src/ETGInstallerSettings.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\ETGInstallerSettings.cs
Extracting: ETGMod.Installer-17.03.29.1/src/ETGModder.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\ETGModder.cs
Extracting: ETGMod.Installer-17.03.29.1/src/InstallerWindow.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\InstallerWindow.cs
Extracting: ETGMod.Installer-17.03.29.1/src/RepoHelper.cs -> C:\GOG Games\Enter the Gungeon\EtG_Data\Managed\ETGMod.Installer-17.03.29.1\src\RepoHelper.cs

Now comes the real "modding" / patching process.
It may seem like the Installer may be stuck sometimes. Go make
yourself a coffee in the meantime - it doesn't get stuck.
It may *crash*, though - and in this case, debug stuff appears
here. Please put that debug stuff onto http://pastebin.com/ and
send it to @0x0ade on Twitter or the #modding channel in Discord.

System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at Mono.Cecil.Mixin.CheckType(Object type)
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultMainRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(MethodReference method, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(ParameterDefinition param, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(IMetadataTokenProvider mtp, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModder.Relink(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.PatchRefsInMethod(MethodDefinition method)
   at MonoMod.MonoModder.PatchRefsInType(TypeDefinition type)
   at MonoMod.MonoModder.PatchRefs()
   at MonoMod.MonoModder.AutoPatch()
   at ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at Mono.Cecil.Mixin.CheckType(Object type)
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultMainRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.DefaultRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(MethodReference method, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(ParameterDefinition param, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModExt.Relink(IMetadataTokenProvider mtp, Relinker relinker, IGenericParameterProvider context)
   at MonoMod.MonoModder.Relink(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   at MonoMod.MonoModder.PatchRefsInMethod(MethodDefinition method)
   at MonoMod.MonoModder.PatchRefsInType(TypeDefinition type)
   at MonoMod.MonoModder.PatchRefs()
   at MonoMod.MonoModder.AutoPatch()
   at ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
   at ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   at ETGModInstaller.ETGModder.Install(InstallerWindow ins)

Will not get passed this.

**Comment by losame2** [comment]
I have the same problem too please help.

**Comment by cormacltighe** [comment]
Same.

**Comment by 0x0ade** [comment]
Please try to run the installer again. It will download the newest "base" build automagically.

I'm not actively working on ETGMod again, but a recent MonoMod update made me recompile ETGMod.

Please check out [this Reddit thread + the "EDIT 2" at the top.](https://www.reddit.com/r/EnterTheGungeon/comments/75qqe9/status_of_mod_the_gungeon/)
