### ISSUE TITLE
ETGMod Installer issue

### ISSUE THREAD

**Issue by zescarecrow** [ModTheGungeon/ETGMod.Installer#18]
System.InvalidOperationException: MonoMod failed relinking Dungeonator.RoomHandler (context: Chest Chest::Spawn(Chest,IntVector2,Dungeonator.RoomHandler,System.Boolean)) ---> System.ArgumentNullException: Wartość nie może być zerowa.
Nazwa parametru: type
   w Mono.Cecil.Mixin.CheckType(Object type)
   w Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
   w MonoMod.MonoModder.DefaultMainRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   w MonoMod.MonoModder.DefaultUncachedRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w MonoMod.MonoModder.DefaultUncachedRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   w MonoMod.MonoModder.DefaultRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   w MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   w MonoMod.MonoModExt.Relink(MethodReference method, Relinker relinker, IGenericParameterProvider context)
   w MonoMod.MonoModExt.Relink(ParameterDefinition param, Relinker relinker, IGenericParameterProvider context)
   w MonoMod.MonoModExt.Relink(IMetadataTokenProvider mtp, Relinker relinker, IGenericParameterProvider context)
   w MonoMod.MonoModder.Relink(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   w MonoMod.MonoModder.PatchRefsInMethod(MethodDefinition method)
   w MonoMod.MonoModder.PatchRefsInType(TypeDefinition type)
   w MonoMod.MonoModder.PatchRefs()
   w MonoMod.MonoModder.AutoPatch()
   w ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
System.InvalidOperationException: MonoMod failed relinking Dungeonator.RoomHandler (context: Chest Chest::Spawn(Chest,IntVector2,Dungeonator.RoomHandler,System.Boolean)) ---> System.ArgumentNullException: Wartość nie może być zerowa.
Nazwa parametru: type
   w Mono.Cecil.Mixin.CheckType(Object type)
   w Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
   w MonoMod.MonoModder.DefaultMainRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   w MonoMod.MonoModder.DefaultUncachedRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w MonoMod.MonoModder.DefaultUncachedRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   w MonoMod.MonoModder.DefaultRelinker(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   w MonoMod.MonoModExt.Relink(TypeReference type, Relinker relinker, IGenericParameterProvider context)
   w MonoMod.MonoModExt.Relink(MethodReference method, Relinker relinker, IGenericParameterProvider context)
   w MonoMod.MonoModExt.Relink(ParameterDefinition param, Relinker relinker, IGenericParameterProvider context)
   w MonoMod.MonoModExt.Relink(IMetadataTokenProvider mtp, Relinker relinker, IGenericParameterProvider context)
   w MonoMod.MonoModder.Relink(IMetadataTokenProvider mtp, IGenericParameterProvider context)
   w MonoMod.MonoModder.PatchRefsInMethod(MethodDefinition method)
   w MonoMod.MonoModder.PatchRefsInType(TypeDefinition type)
   w MonoMod.MonoModder.PatchRefs()
   w MonoMod.MonoModder.AutoPatch()
   w ETGModInstaller.ETGModder.Mod(InstallerWindow ins, String file)
   w ETGModInstaller.ETGModder.Install_(InstallerWindow ins)
   w ETGModInstaller.ETGModder.Install(InstallerWindow ins)

**Comment by rtivital** [comment]
any updates on this?

**Comment by 0x0ade** [comment]
Please try to run the installer again. It will download the newest "base" build automagically.

I'm not actively working on ETGMod again, but a recent MonoMod update made me recompile ETGMod.

Please check out [this Reddit thread + the "EDIT 2" at the top.](https://www.reddit.com/r/EnterTheGungeon/comments/75qqe9/status_of_mod_the_gungeon/)
