### ISSUE TITLE
console isn't working

### ISSUE THREAD

**Issue by Afrokada** [ModTheGungeon/ETGMod.Installer#23]
Yeah um, I press F2 but it only decreases my volume.
Help pls.

**Comment by 0x0ade** [comment]
This isn't the right repository for this issue. Nevertheless, I assume you've got a laptop. In that case, it's your laptop's fault. Have you tried pressing FN + F2?

**Comment by Afrokada** [comment]
Oh, I forgot about that. Thanks it works now.
