### ISSUE TITLE
How to launch this new version mod in MacOS

### ISSUE THREAD

**Issue by XeriTog** [ModTheGungeon/ETGMod.Installer#44]
i'm not good at english, so i can not understood README completely.
the old version just mono it ,can you give me a easily course to launch this?

**Comment by herobrine1q** [comment]
basically, just type "mono --arch=32 " then drag the exe to the terminal. then press enter

**Comment by bumbu** [comment]
`mono --arch=32 ~/Downloads/ETGMod.Installer.exe` replace path with wherever your install is
