### ISSUE TITLE
gog mac enter the gungeon crashes with etgmod installed

### ISSUE THREAD

**Issue by Skriata** [ModTheGungeon/ETGMod.Installer#5]
every time i install the mod using what ever installer that works, the game crashes when trying to load

**Comment by zatherz** [comment]
Temporary workaround - navigate to the Gungeon files and remove all `Galaxy` related DLLs. Please comment if you need more help.

**Comment by Skriata** [comment]
would galaxycsharp be one of them

**Comment by hanselcicada** [comment]
should I delete all(3) files related galaxy in the contents of the Gungeon? 
or just the GalaxyCSharp.dll

**Comment by zatherz** [comment]
Try deleting all of them.

**Comment by hanselcicada** [comment]
<img width="186" alt="2017-02-11 4 56 54" src="https://cloud.githubusercontent.com/assets/25343587/22852837/205d0556-f080-11e6-86a9-b7308e373747.png">
I deleted them but it does not work 😭

**Comment by zatherz** [comment]
@hanselcicada Please test the latest ETGMod release (available in the Installer).

**Comment by hanselcicada** [comment]
@zatherz it works! thankyou sooooo much!
